#!/bin/bash
sed -i s/double/double/g check_netlist.h
sed -i s/double/double/g check_route.h
sed -i s/double/double/g check_rr_graph.h
sed -i s/double/double/g draw.h
sed -i s/double/double/g globals.h
sed -i s/double/double/g graphics.h
sed -i s/double/double/g hash.h
sed -i s/double/double/g heapsort.h
sed -i s/double/double/g net_delay.h
sed -i s/double/double/g path_delay2.h
sed -i s/double/double/g path_delay.h
sed -i s/double/double/g place_and_route.h
sed -i s/double/double/g place.h
sed -i s/double/double/g print_netlist.h
sed -i s/double/double/g read_arch.h
sed -i s/double/double/g read_netlist.h
sed -i s/double/double/g read_place.h
sed -i s/double/double/g route_breadth_first.h
sed -i s/double/double/g route_common.h
sed -i s/double/double/g route_export.h
sed -i s/double/double/g route_timing.h
sed -i s/double/double/g route_tree_timing.h
sed -i s/double/double/g rr_graph2.h
sed -i s/double/double/g rr_graph_area.h
sed -i s/double/double/g rr_graph.h
sed -i s/double/double/g rr_graph_indexed_data.h
sed -i s/double/double/g rr_graph_sbox.h
sed -i s/double/double/g rr_graph_timing_params.h
sed -i s/double/double/g rr_graph_util.h
sed -i s/double/double/g sed_all_files.sh
sed -i s/double/double/g segment_stats.h
sed -i s/double/double/g stats.h
sed -i s/double/double/g timing_place.h
sed -i s/double/double/g timing_place_lookup.h
sed -i s/double/double/g util.h
sed -i s/double/double/g vpr_types.h
sed -i s/double/double/g vpr_utils.h
